## Create LES inputs for 22MW turbine

In [1]:
%load_ext autoreload
%autoreload 2

In [54]:
import numpy as np
from MITRotor import IEA22MW

In [55]:
rotor = IEA22MW()
rotor.R*2

284.0

In [56]:
rotor.hub_radius*2

8.4

In [16]:
# Airfoil names
airfoil_names = np.array(['circular', 'circular', 'FB90', 'FB80', 'FB70', 'FB60', 'SNL-FFA-W3-560FB', 'SNL-FFA-W3-480FB', 'SNL-FFA-W3-420FB', 'FFA-W3-360', 'FFA-W3-330blend', 'FFA-W3-301', 'FFA-W3-270blend', 'FFA-W3-241', 'FFA-W3-211', 'FFA-W3-211'])
airfoil_names

array(['circular', 'circular', 'FB90', 'FB80', 'FB70', 'FB60',
       'SNL-FFA-W3-560FB', 'SNL-FFA-W3-480FB', 'SNL-FFA-W3-420FB',
       'FFA-W3-360', 'FFA-W3-330blend', 'FFA-W3-301', 'FFA-W3-270blend',
       'FFA-W3-241', 'FFA-W3-211', 'FFA-W3-211'], dtype='<U16')

In [17]:
# Airfoil indices cooresponding to demarkations
airfoil_index = np.array([1,1,2,3,4,5,6,7,8,9,10,11,12,13,14,14])
airfoil_index

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 14])

In [18]:
len(airfoil_names) == len(airfoil_index)

True

In [19]:
# Nondimensional airfoil demarkations
airfoil_mu = np.array([0.02957746, 0.04898592, 0.07682068, 0.09410385, 0.11056497, 0.12876342, 0.13667594, 0.16196698, 0.18061830, 0.22041432, 0.26923446, 0.41703187, 0.54738404, 0.74666022, 0.98059074, 1.0])
airfoil_mu

array([0.02957746, 0.04898592, 0.07682068, 0.09410385, 0.11056497,
       0.12876342, 0.13667594, 0.16196698, 0.1806183 , 0.22041432,
       0.26923446, 0.41703187, 0.54738404, 0.74666022, 0.98059074,
       1.        ])

In [20]:
# Dimensional airfoil demarkations
airfoil_r = airfoil_mu * rotor.R
airfoil_r

array([  4.19999932,   6.95600064,  10.90853656,  13.3627467 ,
        15.70022574,  18.28440564,  19.40798348,  22.99931116,
        25.6477986 ,  31.29883344,  38.23129332,  59.21852554,
        77.72853368, 106.02575124, 139.24388508, 142.        ])

In [21]:
# MITRotor twist
twist = np.rad2deg(rotor.twist_func(airfoil_mu))
twist

array([12.        , 11.99902417, 11.98514681, 11.9595266 , 11.91529321,
       11.82970558, 11.7788086 , 11.50829244, 11.16467652,  9.50177104,
        7.0350503 ,  3.36635503,  0.3933288 , -4.17471017, -5.95769907,
       -4.9526063 ])

In [22]:
# MITRotor thickness
thickness = rotor.solidity_func(airfoil_mu)
thickness

array([0.6593563 , 0.39811807, 0.27058362, 0.23065162, 0.20330417,
       0.17987833, 0.17122121, 0.14792812, 0.13389639, 0.1099197 ,
       0.08788187, 0.04709085, 0.02789672, 0.0131952 , 0.00428681,
       0.00134497])

In [23]:
# MITRotor chord length
chord = rotor.chord_func(airfoil_mu)
chord

array([5.8       , 5.80002831, 6.18196597, 6.45521732, 6.68514436,
       6.8883991 , 6.95979712, 7.12564503, 7.19246219, 7.20546993,
       7.03682696, 5.84053639, 4.54142648, 2.93012391, 1.25017055,
       0.4       ])

In [24]:
# Turbine database
for i in range(len(airfoil_r)):
    print("{:7.3f} {:7.4f} {:7.4f} {:8.4f}  {:<18} {:1.0f}".format(
    airfoil_r[i], chord[i], thickness[i], twist[i], f'"{airfoil_names[i]}"', airfoil_index[i]
))

  4.200  5.8000  0.6594  12.0000  "circular"         1
  6.956  5.8000  0.3981  11.9990  "circular"         1
 10.909  6.1820  0.2706  11.9851  "FB90"             2
 13.363  6.4552  0.2307  11.9595  "FB80"             3
 15.700  6.6851  0.2033  11.9153  "FB70"             4
 18.284  6.8884  0.1799  11.8297  "FB60"             5
 19.408  6.9598  0.1712  11.7788  "SNL-FFA-W3-560FB" 6
 22.999  7.1256  0.1479  11.5083  "SNL-FFA-W3-480FB" 7
 25.648  7.1925  0.1339  11.1647  "SNL-FFA-W3-420FB" 8
 31.299  7.2055  0.1099   9.5018  "FFA-W3-360"       9
 38.231  7.0368  0.0879   7.0351  "FFA-W3-330blend"  10
 59.219  5.8405  0.0471   3.3664  "FFA-W3-301"       11
 77.729  4.5414  0.0279   0.3933  "FFA-W3-270blend"  12
106.026  2.9301  0.0132  -4.1747  "FFA-W3-241"       13
139.244  1.2502  0.0043  -5.9577  "FFA-W3-211"       14
142.000  0.4000  0.0013  -4.9526  "FFA-W3-211"       14


In [40]:
aoa = np.linspace(-np.pi, np.pi, 120)

In [41]:
string = 'FB90'

index = 2

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [42]:
string = 'FB80'

index = 3

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [43]:
string = 'FB70'

index = 4

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [44]:
string = 'FB60'

index = 5

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [45]:
string = 'SNL-FFA-W3-560FB'

index = 6

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [46]:
string = 'SNL-FFA-W3-480FB'

index = 7

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [47]:
string = 'SNL-FFA-W3-420FB'

index = 8

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [48]:
string = 'FFA-W3-360'

index = 9

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [49]:
string = 'FFA-W3-330blend'

index = 10

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [50]:
string = 'FFA-W3-301'

index = 11

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [51]:
string = 'FFA-W3-270blend'

index = 12

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [52]:
string = 'FFA-W3-241'

index = 13

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [53]:
string = 'FFA-W3-211'

index = 14

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))