## Create LES inputs for 15MW turbine

In [1]:
%load_ext autoreload
%autoreload 2

In [7]:
import numpy as np
from MITRotor import IEA15MW

In [29]:
rotor = IEA15MW()
rotor.R*2

242.0

In [30]:
rotor.hub_radius*2

7.9

In [9]:
# Airfoil names
airfoil_names = np.array(['circular', 'circular', 'SNL-FFA-W3-500', 'FFA-W3-360', 'FFA-W3-330blend', 'FFA-W3-301', 'FFA-W3-270blend', 'FFA-W3-241', 'FFA-W3-211', 'FFA-W3-211'])
airfoil_names

array(['circular', 'circular', 'SNL-FFA-W3-500', 'FFA-W3-360',
       'FFA-W3-330blend', 'FFA-W3-301', 'FFA-W3-270blend', 'FFA-W3-241',
       'FFA-W3-211', 'FFA-W3-211'], dtype='<U15')

In [10]:
# Airfoil indices cooresponding to demarkations
airfoil_index = np.array([1,1,2,3,4,5,6,7,8,8])
airfoil_index

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])

In [27]:
len(airfoil_names) == len(airfoil_index)

True

In [11]:
# Nondimensional airfoil demarkations
airfoil_mu = np.array([0.03264463, 0.05199174, 0.17774793, 0.26981145, 0.35075359, 0.45748713, 0.55276395, 0.65001823, 0.77919519, 1.0])
airfoil_mu

array([0.03264463, 0.05199174, 0.17774793, 0.26981145, 0.35075359,
       0.45748713, 0.55276395, 0.65001823, 0.77919519, 1.        ])

In [12]:
# Dimensional airfoil demarkations
airfoil_r = airfoil_mu * rotor.R
airfoil_r

array([  3.95000023,   6.29100054,  21.50749953,  32.64718545,
        42.44118439,  55.35594273,  66.88443795,  78.65220583,
        94.28261799, 121.        ])

In [13]:
# MITRotor twist
twist = np.rad2deg(rotor.twist_func(airfoil_mu))
twist

array([15.59455302, 15.58787474, 11.03631313,  7.18281754,  4.73968659,
        2.56654011,  1.22010966,  0.18522748, -1.56742154, -1.24238771])

In [14]:
# MITRotor thickness
thickness = rotor.solidity_func(airfoil_mu)
thickness

array([0.62856126, 0.39531923, 0.12535346, 0.08338856, 0.05793557,
       0.03866205, 0.02830022, 0.0212514 , 0.01467468, 0.001973  ])

In [15]:
# MITRotor chord length
chord = rotor.chord_func(airfoil_mu)
chord

array([5.2       , 5.20866316, 5.64657167, 5.70178501, 5.1498124 ,
       4.48237012, 3.96436332, 3.50071668, 2.89773688, 0.5       ])

In [17]:
# Turbine database
for i in range(len(airfoil_r)):
    print("{:7.3f} {:7.4f} {:7.4f} {:8.4f}  {:<18} {:1.0f}".format(
    airfoil_r[i], chord[i], thickness[i], twist[i], f'"{airfoil_names[i]}"', airfoil_index[i]
))

  3.950  5.2000  0.6286  15.5946  "circular"         1
  6.291  5.2087  0.3953  15.5879  "circular"         1
 21.507  5.6466  0.1254  11.0363  "SNL-FFA-W3-500"   2
 32.647  5.7018  0.0834   7.1828  "FFA-W3-360"       3
 42.441  5.1498  0.0579   4.7397  "FFA-W3-330blend"  4
 55.356  4.4824  0.0387   2.5665  "FFA-W3-301"       5
 66.884  3.9644  0.0283   1.2201  "FFA-W3-270blend"  6
 78.652  3.5007  0.0213   0.1852  "FFA-W3-241"       7
 94.283  2.8977  0.0147  -1.5674  "FFA-W3-211"       8
121.000  0.5000  0.0020  -1.2424  "FFA-W3-211"       8


In [40]:
aoa = np.linspace(-np.pi, np.pi, 120)

In [41]:
string = 'SNL-FFA-W3-500'

index = 2

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR\n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [42]:
string = 'FFA-W3-360'

index = 3

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR\n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [43]:
string = 'FFA-W3-330blend'

index = 4

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR\n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [44]:
string = 'FFA-W3-301'

index = 5

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR\n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [45]:
string = 'FFA-W3-270blend'

index = 6

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR\n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [46]:
string = 'FFA-W3-241'

index = 7

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR\n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [47]:
string = 'FFA-W3-211'

index = 8

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR\n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))