## Create LES inputs for 10MW turbine

In [1]:
%load_ext autoreload
%autoreload 2

In [4]:
import numpy as np
from MITRotor import IEA10MW

In [5]:
rotor = IEA10MW()
rotor.R*2

199.0

In [6]:
rotor.hub_radius*2

4.8

In [7]:
# Airfoil names
airfoil_names = np.array(['cylinder', 'cylinder', 'FFA-W3-360', 'FFA-W3-330blend', 'FFA-W3-301', 'FFA-W3-270blend', 'FFA-W3-241', 'FFA-W3-211'])
airfoil_names

array(['cylinder', 'cylinder', 'FFA-W3-360', 'FFA-W3-330blend',
       'FFA-W3-301', 'FFA-W3-270blend', 'FFA-W3-241', 'FFA-W3-211'],
      dtype='<U15')

In [8]:
# Airfoil indices cooresponding to demarkations
airfoil_index = np.array([1,1,2,3,4,5,6,7])
airfoil_index

array([1, 1, 2, 3, 4, 5, 6, 7])

In [9]:
len(airfoil_names) == len(airfoil_index)

True

In [10]:
# Nondimensional airfoil demarkations
airfoil_mu = np.array([0.0241206,  0.0338794,  0.21441709, 0.26028342, 0.5071809,  0.59501005, 0.69259799, 1.0])
airfoil_mu

array([0.0241206 , 0.0338794 , 0.21441709, 0.26028342, 0.5071809 ,
       0.59501005, 0.69259799, 1.        ])

In [11]:
# Dimensional airfoil demarkations
airfoil_r = airfoil_mu * rotor.R
airfoil_r

array([ 2.3999997 ,  3.3710003 , 21.33450046, 25.89820029, 50.46449955,
       59.20349997, 68.91350001, 99.5       ])

In [12]:
# MITRotor twist
twist = np.rad2deg(rotor.twist_func(airfoil_mu))
twist

array([12.00002806, 11.9999155 ,  8.75357581,  6.56698695,  2.18099673,
        0.57284115, -1.1850658 , -0.03724226])

In [13]:
# MITRotor thickness
thickness = rotor.solidity_func(airfoil_mu)
thickness

array([9.15141037e-01, 6.51656359e-01, 1.32971688e-01, 1.10238209e-01,
       3.80150046e-02, 2.63073552e-02, 1.76966061e-02, 4.61629312e-04])

In [14]:
# MITRotor chord length
chord = rotor.chord_func(airfoil_mu)
chord

array([4.6       , 4.60082847, 5.94155706, 5.97943771, 4.0179047 ,
       3.2619942 , 2.55418826, 0.0962    ])

In [15]:
# Turbine database
for i in range(len(airfoil_r)):
    print("{:6.3f} {:7.4f} {:7.4f} {:8.4f}  {:<18} {:1.0f}".format(
    airfoil_r[i], chord[i], thickness[i], twist[i], f'"{airfoil_names[i]}"', airfoil_index[i]
))

 2.400  4.6000  0.9151  12.0000  "cylinder"         1
 3.371  4.6008  0.6517  11.9999  "cylinder"         1
21.335  5.9416  0.1330   8.7536  "FFA-W3-360"       2
25.898  5.9794  0.1102   6.5670  "FFA-W3-330blend"  3
50.464  4.0179  0.0380   2.1810  "FFA-W3-301"       4
59.203  3.2620  0.0263   0.5728  "FFA-W3-270blend"  5
68.914  2.5542  0.0177  -1.1851  "FFA-W3-241"       6
99.500  0.0962  0.0005  -0.0372  "FFA-W3-211"       7


In [16]:
aoa = np.linspace(-np.pi, np.pi, 120)

In [17]:
string = 'FFA-W3-360'

index = 2

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [18]:
string = 'FFA-W3-330blend'

index = 3

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [19]:
string = 'FFA-W3-301'

index = 4

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [20]:
string = 'FFA-W3-270blend'

index = 5

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [21]:
string = 'FFA-W3-241'

index = 6

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))

In [22]:
string = 'FFA-W3-211'

index = 7

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

with open(f'./airfoil_tables/{string}.dat', "w") as f:
    f.write(f'{len(aoa)} "Cl" "Cd" "Cm" GENERATED FROM MITROTOR \n')
    for i in range(len(aoa)):
        f.write("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f}\n".format(
        np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
    ))