In [3]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
import numpy as np
from MITRotor import IEA10MW

In [5]:
rotor = IEA10MW()

In [6]:
# Airfoil names
airfoil_names = np.array(['cylinder', 'cylinder', 'FFA-W3-360', 'FFA-W3-330blend', 'FFA-W3-301', 'FFA-W3-270blend', 'FFA-W3-241', 'FFA-W3-211'])
airfoil_names

array(['cylinder', 'cylinder', 'FFA-W3-360', 'FFA-W3-330blend',
       'FFA-W3-301', 'FFA-W3-270blend', 'FFA-W3-241', 'FFA-W3-211'],
      dtype='<U15')

In [7]:
# Airfoil indices cooresponding to demarkations
airfoil_index = np.array([1,1,2,3,4,5,6,7])
airfoil_index

array([1, 1, 2, 3, 4, 5, 6, 7])

In [8]:
# Nondimensional airfoil demarkations
airfoil_mu = np.array([0.0241206,  0.0338794,  0.21441709, 0.26028342, 0.5071809,  0.59501005, 0.69259799, 1.0])
airfoil_mu

array([0.0241206 , 0.0338794 , 0.21441709, 0.26028342, 0.5071809 ,
       0.59501005, 0.69259799, 1.        ])

In [9]:
# Dimensional airfoil demarkations
airfoil_r = airfoil_mu * 99.5
airfoil_r

array([ 2.3999997 ,  3.3710003 , 21.33450046, 25.89820029, 50.46449955,
       59.20349997, 68.91350001, 99.5       ])

In [10]:
# MITRotor twist
twist = np.rad2deg(rotor.twist_func(airfoil_mu))
twist

array([12.00002806, 11.9999155 ,  8.75357581,  6.56698695,  2.18099673,
        0.57284115, -1.1850658 , -0.03724226])

In [11]:
# MITRotor thickness
thickness = rotor.solidity_func(airfoil_mu)
thickness

array([9.15141037e-01, 6.51656359e-01, 1.32971688e-01, 1.10238209e-01,
       3.80150046e-02, 2.63073552e-02, 1.76966061e-02, 4.61629312e-04])

In [12]:
# MITRotor chord length
chord = rotor.chord_func(airfoil_mu)
chord

array([4.6       , 4.60082847, 5.94155706, 5.97943771, 4.0179047 ,
       3.2619942 , 2.55418826, 0.0962    ])

In [13]:
# Turbine database
for i in range(len(airfoil_r)):
    print("{:6.3f} {:7.4f} {:7.4f} {:8.4f}  {:<18} {:1.0f}".format(
    airfoil_r[i], chord[i], thickness[i], twist[i], f'"{airfoil_names[i]}"', airfoil_index[i]
))

 2.400  4.6000  0.9151  12.0000  "cylinder"         1
 3.371  4.6008  0.6517  11.9999  "cylinder"         1
21.335  5.9416  0.1330   8.7536  "FFA-W3-360"       2
25.898  5.9794  0.1102   6.5670  "FFA-W3-330blend"  3
50.464  4.0179  0.0380   2.1810  "FFA-W3-301"       4
59.203  3.2620  0.0263   0.5728  "FFA-W3-270blend"  5
68.914  2.5542  0.0177  -1.1851  "FFA-W3-241"       6
99.500  0.0962  0.0005  -0.0372  "FFA-W3-211"       7


In [15]:
aoa = np.linspace(-np.pi, np.pi, 120)

In [16]:
# FFA-W3-360

index = 2

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

# Print row by row
for i in range(len(aoa)):
    print("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f} ".format(
    np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
))

-180.000   0.0000   0.0371   0.0000 
-176.975   0.0950   0.0383   0.0000 
-173.950   0.1900   0.0414   0.0000 
-170.924   0.2850   0.0464   0.0000 
-167.899   0.3800   0.0544   0.0000 
-164.874   0.4750   0.0766   0.0000 
-161.849   0.5700   0.1141   0.0000 
-158.824   0.6650   0.1580   0.0000 
-155.798   0.7600   0.2072   0.0000 
-152.773   0.8550   0.2609   0.0000 
-149.748   0.9500   0.3191   0.0000 
-146.723   0.9784   0.3813   0.0000 
-143.697   0.9161   0.4455   0.0000 
-140.672   0.8614   0.5125   0.0000 
-137.647   0.8095   0.5808   0.0000 
-134.622   0.7595   0.6496   0.0000 
-131.597   0.7106   0.7186   0.0000 
-128.571   0.6619   0.7864   0.0000 
-125.546   0.6127   0.8527   0.0000 
-122.521   0.5629   0.9170   0.0000 
-119.496   0.5122   0.9782   0.0000 
-116.471   0.4604   1.0351   0.0000 
-113.445   0.4078   1.0881   0.0000 
-110.420   0.3546   1.1369   0.0000 
-107.395   0.3007   1.1791   0.0000 
-104.370   0.2467   1.2153   0.0000 
-101.345   0.1930   1.2460   0.0000 
 

In [17]:
# FFA-W3-330blend

index = 3

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

# Print row by row
for i in range(len(aoa)):
    print("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f} ".format(
    np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
))

-180.000   0.0000   0.0317   0.0000 
-176.975   0.0921   0.0329   0.0000 
-173.950   0.1842   0.0360   0.0000 
-170.924   0.2764   0.0410   0.0000 
-167.899   0.3685   0.0496   0.0000 
-164.874   0.4606   0.0733   0.0000 
-161.849   0.5527   0.1109   0.0000 
-158.824   0.6448   0.1548   0.0000 
-155.798   0.7370   0.2040   0.0000 
-152.773   0.8291   0.2578   0.0000 
-149.748   0.9212   0.3161   0.0000 
-146.723   0.9497   0.3784   0.0000 
-143.697   0.8914   0.4427   0.0000 
-140.672   0.8401   0.5099   0.0000 
-137.647   0.7912   0.5782   0.0000 
-134.622   0.7439   0.6472   0.0000 
-131.597   0.6974   0.7163   0.0000 
-128.571   0.6506   0.7842   0.0000 
-125.546   0.6033   0.8507   0.0000 
-122.521   0.5552   0.9152   0.0000 
-119.496   0.5059   0.9765   0.0000 
-116.471   0.4553   1.0335   0.0000 
-113.445   0.4039   1.0867   0.0000 
-110.420   0.3516   1.1357   0.0000 
-107.395   0.2986   1.1781   0.0000 
-104.370   0.2453   1.2144   0.0000 
-101.345   0.1921   1.2453   0.0000 
 

In [18]:
# FFA-W3-301

index = 4

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

# Print row by row
for i in range(len(aoa)):
    print("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f} ".format(
    np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
))

-180.000   0.0000   0.0245   0.0000 
-176.975   0.0861   0.0257   0.0000 
-173.950   0.1723   0.0289   0.0000 
-170.924   0.2584   0.0340   0.0000 
-167.899   0.3446   0.0452   0.0000 
-164.874   0.4307   0.0751   0.0000 
-161.849   0.5168   0.1126   0.0000 
-158.824   0.6030   0.1565   0.0000 
-155.798   0.6891   0.2057   0.0000 
-152.773   0.7752   0.2594   0.0000 
-149.748   0.8614   0.3177   0.0000 
-146.723   0.8900   0.3799   0.0000 
-143.697   0.8402   0.4442   0.0000 
-140.672   0.7959   0.5113   0.0000 
-137.647   0.7532   0.5796   0.0000 
-134.622   0.7114   0.6484   0.0000 
-131.597   0.6699   0.7175   0.0000 
-128.571   0.6274   0.7854   0.0000 
-125.546   0.5838   0.8517   0.0000 
-122.521   0.5392   0.9162   0.0000 
-119.496   0.4929   0.9774   0.0000 
-116.471   0.4449   1.0343   0.0000 
-113.445   0.3958   1.0874   0.0000 
-110.420   0.3456   1.1364   0.0000 
-107.395   0.2942   1.1786   0.0000 
-104.370   0.2422   1.2149   0.0000 
-101.345   0.1902   1.2456   0.0000 
 

In [19]:
# FFA-W3-270blend

index = 5

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

# Print row by row
for i in range(len(aoa)):
    print("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f} ".format(
    np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
))

-180.000   0.0000   0.0155   0.0000 
-176.975   0.0822   0.0167   0.0000 
-173.950   0.1645   0.0202   0.0000 
-170.924   0.2467   0.0257   0.0000 
-167.899   0.3289   0.0399   0.0000 
-164.874   0.4111   0.0740   0.0000 
-161.849   0.4934   0.1146   0.0000 
-158.824   0.5756   0.1620   0.0000 
-155.798   0.6578   0.2151   0.0000 
-152.773   0.7401   0.2731   0.0000 
-149.748   0.8223   0.3361   0.0000 
-146.723   0.8534   0.4033   0.0000 
-143.697   0.8147   0.4726   0.0000 
-140.672   0.7793   0.5452   0.0000 
-137.647   0.7443   0.6189   0.0000 
-134.622   0.7091   0.6934   0.0000 
-131.597   0.6730   0.7680   0.0000 
-128.571   0.6346   0.8414   0.0000 
-125.546   0.5945   0.9132   0.0000 
-122.521   0.5524   0.9828   0.0000 
-119.496   0.5079   1.0492   0.0000 
-116.471   0.4608   1.1108   0.0000 
-113.445   0.4119   1.1683   0.0000 
-110.420   0.3614   1.2213   0.0000 
-107.395   0.3090   1.2672   0.0000 
-104.370   0.2555   1.3066   0.0000 
-101.345   0.2015   1.3401   0.0000 
 

In [20]:
# FFA-W3-241

index = 6

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

# Print row by row
for i in range(len(aoa)):
    print("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f} ".format(
    np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
))

-180.000   0.0000   0.0118   0.0000 
-176.975   0.0770   0.0132   0.0000 
-173.950   0.1540   0.0169   0.0000 
-170.924   0.2310   0.0229   0.0000 
-167.899   0.3080   0.0365   0.0000 
-164.874   0.3850   0.0723   0.0000 
-161.849   0.4620   0.1159   0.0000 
-158.824   0.5390   0.1668   0.0000 
-155.798   0.6160   0.2239   0.0000 
-152.773   0.6930   0.2862   0.0000 
-149.748   0.7700   0.3538   0.0000 
-146.723   0.8036   0.4260   0.0000 
-143.697   0.7779   0.5006   0.0000 
-140.672   0.7530   0.5785   0.0000 
-137.647   0.7270   0.6578   0.0000 
-134.622   0.6995   0.7378   0.0000 
-131.597   0.6700   0.8180   0.0000 
-128.571   0.6367   0.8970   0.0000 
-125.546   0.6008   0.9742   0.0000 
-122.521   0.5621   1.0491   0.0000 
-119.496   0.5200   1.1205   0.0000 
-116.471   0.4743   1.1869   0.0000 
-113.445   0.4263   1.2488   0.0000 
-110.420   0.3760   1.3060   0.0000 
-107.395   0.3229   1.3556   0.0000 
-104.370   0.2682   1.3981   0.0000 
-101.345   0.2123   1.4344   0.0000 
 

In [21]:
# FFA-W3-211

index = 7

ref_CL = rotor.airfoil_func.cl_2d_raw[index,:]
ref_CD = rotor.airfoil_func.cd_2d_raw[index,:]

# Print row by row
for i in range(len(aoa)):
    print("{:8.3f}  {:7.4f}  {:7.4f}  {:7.4f} ".format(
    np.rad2deg(aoa[i]), ref_CL[i], ref_CD[i], 0.0
))

-180.000   0.0000   0.0246   0.0000 
-176.975   0.0715   0.0260   0.0000 
-173.950   0.1430   0.0297   0.0000 
-170.924   0.2145   0.0356   0.0000 
-167.899   0.2860   0.0635   0.0000 
-164.874   0.3575   0.0998   0.0000 
-161.849   0.4290   0.1429   0.0000 
-158.824   0.5005   0.1933   0.0000 
-155.798   0.5720   0.2498   0.0000 
-152.773   0.6435   0.3115   0.0000 
-149.748   0.7150   0.3784   0.0000 
-146.723   0.7488   0.4498   0.0000 
-143.697   0.7309   0.5235   0.0000 
-140.672   0.7124   0.6005   0.0000 
-137.647   0.6921   0.6788   0.0000 
-134.622   0.6697   0.7578   0.0000 
-131.597   0.6447   0.8369   0.0000 
-128.571   0.6154   0.9147   0.0000 
-125.546   0.5829   0.9907   0.0000 
-122.521   0.5474   1.0644   0.0000 
-119.496   0.5080   1.1345   0.0000 
-116.471   0.4648   1.1995   0.0000 
-113.445   0.4189   1.2601   0.0000 
-110.420   0.3704   1.3160   0.0000 
-107.395   0.3189   1.3640   0.0000 
-104.370   0.2654   1.4052   0.0000 
-101.345   0.2106   1.4400   0.0000 
 